baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-initio"

[params]
	name = "squidwrench"
	description = "The First Hudson Valley Hackerspace"
	showSubheader = true
	showServices = true
	showRecentWorks = true
	showDownload = true
	showClients = true
	DateForm = "2 January 2006"
